from __future__ import annotations


REQUIRED_COLUMNS: tuple[str, ...] = (
    "Stock",
    "Signals today",
    "Rank",
    "Exp/DAY%",
    "RS%",
    "Trades",
    "Win%",
    "Target #",
    "Target %",
    "Trail #",
    "Trail %",
    "Stop #",
    "Stop %",
    "Time #",
    "Time %",
    "Time-win",
    "Time-loss",
    "MomExit #",
    "MomExit %",
    "Decay #",
    "Decay %",
    "Staircase #",
    "Expectancy%",
    "Avg win%",
    "Avg loss%",
    "R:R",
    "Avg days",
    "Total return (sum)%",
    "CAGR%",
    "Max DD%",
    "Profit factor",
    "Recovery factor",
    "Max consec. losses",
    "Seq. trades",
    "BT from",
    "BT to",
    "Years",
    "Remark",
)


NUMERIC_COLUMNS: tuple[str, ...] = (
    "Rank",
    "Exp/DAY%",
    "RS%",
    "Trades",
    "Win%",
    "Target #",
    "Target %",
    "Trail #",
    "Trail %",
    "Stop #",
    "Stop %",
    "Time #",
    "Time %",
    "Time-win",
    "Time-loss",
    "MomExit #",
    "MomExit %",
    "Decay #",
    "Decay %",
    "Staircase #",
    "Expectancy%",
    "Avg win%",
    "Avg loss%",
    "R:R",
    "Avg days",
    "Total return (sum)%",
    "CAGR%",
    "Max DD%",
    "Profit factor",
    "Recovery factor",
    "Max consec. losses",
    "Seq. trades",
    "Years",
)